added title names in breadcrumbs for several different video display …
BYU-ODH/yvideo-client pull request #726
Opened 2022-10-06 15:57 UTC by alexander-densley

…sections

2022-10-06 23:18 UTC, reynoldsnlp requested changes
@Aaron-M-Anderson and I had talked about putting the name in parentheses (without a preceding `|`, since the pipe indicates a navigational step). So if you concatenate the name with `Player`, I think that will be a little more clear.

2022-10-12 17:45 UTC, Aaron-M-Anderson approved these changes

2022-10-12 17:57 UTC, Aaron-M-Anderson approved these changes

2022-10-12 20:38 UTC, reynoldsnlp approved these changes
lgtm

2022-10-12 21:45 UTC, merged