774 Change all alert message for sweetalert message
BYU-ODH/yvideo-client pull request #813
Opened 2022-11-25 20:51 UTC by jtabilot

Change all the alert native message for Sweetalert

2022-11-28 23:43 UTC, reynoldsnlp requested changes
I prefer avoiding new dependencies whenever possible. Can this be done without `sweetalert2`? For example, since we are already adopting `react-bootstrap`, does it include the functionality we need?

2022-11-29 00:02 UTC, jtabilot commented
> I prefer avoiding new dependencies whenever possible. Can this be done without `sweetalert2`? For example, since we are already adopting `react-bootstrap`, does it include the functionality we need?

@reynoldsnlp I gree with you about avoid including new depencies, however sweetalert was already installed in the proyect. On other hand, as far as I know bootstrap dosen't have native modals like sweetalert, I mean you need to define the modal in your html code, instead sweetalert gives you all the code already implemented. 
Now answering your question about if this can be done witout sweetalert, yes, but it will implicate to write an html modal.

2022-11-29 01:30 UTC, Aaron-M-Anderson approved these changes

2022-11-29 20:02 UTC, reynoldsnlp approved these changes
lgtm

2022-11-29 20:02 UTC, merged